import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportMonthlyPayrollPDF = (data) => {
  const doc = new jsPDF();
  
  // Format currency
  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amount || 0);
  };

  // Header Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(79, 70, 229); // #4F46E5 (indigo-600)
  doc.text('PayFlow', 14, 20);

  doc.setFontSize(16);
  doc.setTextColor(51, 65, 85); // Slate-700
  doc.text('Monthly Payroll Report', 14, 30);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(`${data.month} ${data.year}`, 14, 38);
  
  doc.setFontSize(10);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 44);

  // Horizontal line separator
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.line(14, 50, 196, 50);

  // Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Payroll Summary', 14, 62);

  // 4 Info Boxes
  const boxY = 68;
  const boxWidth = 42;
  const boxHeight = 20;
  const startX = 14;
  const gap = 4;

  const summaryData = [
    { label: 'Total Payroll', value: formatCurrency(data.totalPayroll) },
    { label: 'Total Employees', value: data.totalEmployees?.toString() || '0' },
    { label: 'Avg. Salary', value: formatCurrency(data.avgSalary) },
    { label: 'Total Deductions', value: formatCurrency(data.totalDeductions) }
  ];

  doc.setFontSize(9);
  summaryData.forEach((item, index) => {
    const x = startX + (boxWidth + gap) * index;
    
    // Box
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, boxY, boxWidth, boxHeight, 2, 2, 'FD');

    // Label
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(item.label, x + 4, boxY + 7);

    // Value
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(item.value, x + 4, boxY + 15);
  });

  // Employee Details Table
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Employee Breakdown', 14, 102);

  const tableData = (data.employees || []).map((emp, index) => [
    index + 1,
    emp.name,
    emp.role || emp.department || 'N/A',
    formatCurrency(emp.baseSalary),
    formatCurrency(emp.deductions),
    formatCurrency(emp.netPay),
    emp.status || 'Paid'
  ]);

  autoTable(doc, {
    startY: 108,
    head: [['#', 'Employee Name', 'Department', 'Base Salary', 'Deductions', 'Net Pay', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    styles: {
      font: 'helvetica',
      fontSize: 9,
      textColor: [51, 65, 85],
      lineColor: [226, 232, 240],
      lineWidth: 0.1
    },
    margin: { left: 14, right: 14 },
    showHead: 'firstPage'
  });

  // Footer Section
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.height;
    
    doc.setDrawColor(226, 232, 240);
    doc.line(14, pageHeight - 20, 196, pageHeight - 20);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate-400
    
    doc.text('Generated by PayFlow Payroll System', 14, pageHeight - 12);
    doc.text('Confidential - For Internal Use Only', 14, pageHeight - 8);
    
    const pageString = `Page ${i} of ${pageCount}`;
    const pageWidth = doc.internal.pageSize.width;
    const textWidth = doc.getStringUnitWidth(pageString) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    doc.text(pageString, pageWidth - 14 - textWidth, pageHeight - 12);
  }

  // Save PDF
  doc.save(`PayFlow_Monthly_Report_${data.month}_${data.year}.pdf`);
};
